version: "2"

run:
  timeout: 5m
  allow-parallel-runners: true

formatters:
  enable:
  - goimports
  - gofmt

linters:
  enable:
  - copyloopvar
  - dupword
  - durationcheck
  - fatcontext
  - ginkgolinter
  - gocritic
  - govet
  - loggercheck
  - misspell
  - perfsprint
  - revive
  - unconvert
  - makezero
  - errcheck
  - goconst
  - ineffassign
  - nakedret
  - prealloc
  - unparam
  - unused

linters-settings:
    revive:
      rules:
        - name: dot-imports
          arguments:
            - allowedPackages:
              - "github.com/onsi/ginkgo"
              - "github.com/onsi/ginkgo/v2"
              - "github.com/onsi/gomega"
